/* tslint:disable */
/* eslint-disable */
/**
 * Once Upon
 * API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddressWithChainIdDto
 */
export interface AddressWithChainIdDto {
    /**
     * List of chain IDs associated with the address.
     * @type {Array<number>}
     * @memberof AddressWithChainIdDto
     */
    chainIds: Array<number>;
    /**
     * The address.
     * @type {string}
     * @memberof AddressWithChainIdDto
     */
    address: string;
}

/**
 * Check if a given object implements the AddressWithChainIdDto interface.
 */
export function instanceOfAddressWithChainIdDto(value: object): boolean {
    if (!('chainIds' in value)) return false;
    if (!('address' in value)) return false;
    return true;
}

export function AddressWithChainIdDtoFromJSON(json: any): AddressWithChainIdDto {
    return AddressWithChainIdDtoFromJSONTyped(json, false);
}

export function AddressWithChainIdDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddressWithChainIdDto {
    if (json == null) {
        return json;
    }
    return {
        
        'chainIds': json['chainIds'],
        'address': json['address'],
    };
}

export function AddressWithChainIdDtoToJSON(value?: AddressWithChainIdDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'chainIds': value['chainIds'],
        'address': value['address'],
    };
}

