/* tslint:disable */
/* eslint-disable */
/**
 * Once Upon
 * API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddressTag
 */
export interface AddressTag {
    /**
     * Address value
     * @type {string}
     * @memberof AddressTag
     */
    address: string;
    /**
     * To/From or All indication
     * @type {string}
     * @memberof AddressTag
     */
    toFromAll: AddressTagToFromAllEnum;
}


/**
 * @export
 */
export const AddressTagToFromAllEnum = {
    ToFrom: 'To/From',
    All: 'All',
    To: 'To',
    From: 'From'
} as const;
export type AddressTagToFromAllEnum = typeof AddressTagToFromAllEnum[keyof typeof AddressTagToFromAllEnum];


/**
 * Check if a given object implements the AddressTag interface.
 */
export function instanceOfAddressTag(value: object): boolean {
    if (!('address' in value)) return false;
    if (!('toFromAll' in value)) return false;
    return true;
}

export function AddressTagFromJSON(json: any): AddressTag {
    return AddressTagFromJSONTyped(json, false);
}

export function AddressTagFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddressTag {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'],
        'toFromAll': json['toFromAll'],
    };
}

export function AddressTagToJSON(value?: AddressTag | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'address': value['address'],
        'toFromAll': value['toFromAll'],
    };
}

