/* tslint:disable */
/* eslint-disable */
/**
 * Once Upon
 * API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AssetDto
 */
export interface AssetDto {
    /**
     * Asset
     * @type {string}
     * @memberof AssetDto
     */
    asset: string;
    /**
     * ID
     * @type {string}
     * @memberof AssetDto
     */
    id: string;
    /**
     * Type
     * @type {string}
     * @memberof AssetDto
     */
    type: AssetDtoTypeEnum;
    /**
     * Value
     * @type {string}
     * @memberof AssetDto
     */
    value: string;
    /**
     * Token ID
     * @type {string}
     * @memberof AssetDto
     */
    tokenId: string;
}


/**
 * @export
 */
export const AssetDtoTypeEnum = {
    Eth: 'eth',
    Erc20: 'erc20',
    Erc721: 'erc721',
    Erc1155: 'erc1155'
} as const;
export type AssetDtoTypeEnum = typeof AssetDtoTypeEnum[keyof typeof AssetDtoTypeEnum];


/**
 * Check if a given object implements the AssetDto interface.
 */
export function instanceOfAssetDto(value: object): boolean {
    if (!('asset' in value)) return false;
    if (!('id' in value)) return false;
    if (!('type' in value)) return false;
    if (!('value' in value)) return false;
    if (!('tokenId' in value)) return false;
    return true;
}

export function AssetDtoFromJSON(json: any): AssetDto {
    return AssetDtoFromJSONTyped(json, false);
}

export function AssetDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssetDto {
    if (json == null) {
        return json;
    }
    return {
        
        'asset': json['asset'],
        'id': json['id'],
        'type': json['type'],
        'value': json['value'],
        'tokenId': json['tokenId'],
    };
}

export function AssetDtoToJSON(value?: AssetDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'asset': value['asset'],
        'id': value['id'],
        'type': value['type'],
        'value': value['value'],
        'tokenId': value['tokenId'],
    };
}

