/* tslint:disable */
/* eslint-disable */
/**
 * Once Upon
 * API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AssetTransferDto
 */
export interface AssetTransferDto {
    /**
     * Asset
     * @type {string}
     * @memberof AssetTransferDto
     */
    asset: string;
    /**
     * Sender address
     * @type {string}
     * @memberof AssetTransferDto
     */
    from: string;
    /**
     * Receiver address
     * @type {string}
     * @memberof AssetTransferDto
     */
    to: string;
    /**
     * Type
     * @type {string}
     * @memberof AssetTransferDto
     */
    type: AssetTransferDtoTypeEnum;
    /**
     * Value
     * @type {string}
     * @memberof AssetTransferDto
     */
    value: string;
    /**
     * Token ID
     * @type {string}
     * @memberof AssetTransferDto
     */
    tokenId: string;
}


/**
 * @export
 */
export const AssetTransferDtoTypeEnum = {
    Eth: 'eth',
    Erc20: 'erc20',
    Erc721: 'erc721',
    Erc1155: 'erc1155'
} as const;
export type AssetTransferDtoTypeEnum = typeof AssetTransferDtoTypeEnum[keyof typeof AssetTransferDtoTypeEnum];


/**
 * Check if a given object implements the AssetTransferDto interface.
 */
export function instanceOfAssetTransferDto(value: object): boolean {
    if (!('asset' in value)) return false;
    if (!('from' in value)) return false;
    if (!('to' in value)) return false;
    if (!('type' in value)) return false;
    if (!('value' in value)) return false;
    if (!('tokenId' in value)) return false;
    return true;
}

export function AssetTransferDtoFromJSON(json: any): AssetTransferDto {
    return AssetTransferDtoFromJSONTyped(json, false);
}

export function AssetTransferDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssetTransferDto {
    if (json == null) {
        return json;
    }
    return {
        
        'asset': json['asset'],
        'from': json['from'],
        'to': json['to'],
        'type': json['type'],
        'value': json['value'],
        'tokenId': json['tokenId'],
    };
}

export function AssetTransferDtoToJSON(value?: AssetTransferDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'asset': value['asset'],
        'from': value['from'],
        'to': value['to'],
        'type': value['type'],
        'value': value['value'],
        'tokenId': value['tokenId'],
    };
}

