/* tslint:disable */
/* eslint-disable */
/**
 * Once Upon
 * API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BlockDto
 */
export interface BlockDto {
    /**
     * ID of the chain.
     * @type {number}
     * @memberof BlockDto
     */
    chainId: number;
    /**
     * Number of the block.
     * @type {number}
     * @memberof BlockDto
     */
    number: number;
    /**
     * Timestamp of the block.
     * @type {number}
     * @memberof BlockDto
     */
    timestamp: number;
    /**
     * Price of the block. Optional.
     * @type {number}
     * @memberof BlockDto
     */
    price?: number;
}

/**
 * Check if a given object implements the BlockDto interface.
 */
export function instanceOfBlockDto(value: object): boolean {
    if (!('chainId' in value)) return false;
    if (!('number' in value)) return false;
    if (!('timestamp' in value)) return false;
    return true;
}

export function BlockDtoFromJSON(json: any): BlockDto {
    return BlockDtoFromJSONTyped(json, false);
}

export function BlockDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BlockDto {
    if (json == null) {
        return json;
    }
    return {
        
        'chainId': json['chainId'],
        'number': json['number'],
        'timestamp': json['timestamp'],
        'price': json['price'] == null ? undefined : json['price'],
    };
}

export function BlockDtoToJSON(value?: BlockDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'chainId': value['chainId'],
        'number': value['number'],
        'timestamp': value['timestamp'],
        'price': value['price'],
    };
}

