/* tslint:disable */
/* eslint-disable */
/**
 * Once Upon
 * API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaymentTokenDto } from './PaymentTokenDto';
import {
    PaymentTokenDtoFromJSON,
    PaymentTokenDtoFromJSONTyped,
    PaymentTokenDtoToJSON,
} from './PaymentTokenDto';

/**
 * 
 * @export
 * @interface CollectionFloorPriceDto
 */
export interface CollectionFloorPriceDto {
    /**
     * The ID of the marketplace
     * @type {string}
     * @memberof CollectionFloorPriceDto
     */
    marketplaceId: string;
    /**
     * Name of the marketplace
     * @type {string}
     * @memberof CollectionFloorPriceDto
     */
    marketplaceName: string;
    /**
     * Value of the transaction
     * @type {number}
     * @memberof CollectionFloorPriceDto
     */
    value: number;
    /**
     * Details of the payment token
     * @type {PaymentTokenDto}
     * @memberof CollectionFloorPriceDto
     */
    paymentToken: PaymentTokenDto;
    /**
     * Value in USD cents
     * @type {number}
     * @memberof CollectionFloorPriceDto
     */
    valueUsdCents: number;
}

/**
 * Check if a given object implements the CollectionFloorPriceDto interface.
 */
export function instanceOfCollectionFloorPriceDto(value: object): boolean {
    if (!('marketplaceId' in value)) return false;
    if (!('marketplaceName' in value)) return false;
    if (!('value' in value)) return false;
    if (!('paymentToken' in value)) return false;
    if (!('valueUsdCents' in value)) return false;
    return true;
}

export function CollectionFloorPriceDtoFromJSON(json: any): CollectionFloorPriceDto {
    return CollectionFloorPriceDtoFromJSONTyped(json, false);
}

export function CollectionFloorPriceDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionFloorPriceDto {
    if (json == null) {
        return json;
    }
    return {
        
        'marketplaceId': json['marketplace_id'],
        'marketplaceName': json['marketplace_name'],
        'value': json['value'],
        'paymentToken': PaymentTokenDtoFromJSON(json['payment_token']),
        'valueUsdCents': json['value_usd_cents'],
    };
}

export function CollectionFloorPriceDtoToJSON(value?: CollectionFloorPriceDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'marketplace_id': value['marketplaceId'],
        'marketplace_name': value['marketplaceName'],
        'value': value['value'],
        'payment_token': PaymentTokenDtoToJSON(value['paymentToken']),
        'value_usd_cents': value['valueUsdCents'],
    };
}

