/* tslint:disable */
/* eslint-disable */
/**
 * Once Upon
 * API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PaymentTokenDto } from './PaymentTokenDto';
import {
    PaymentTokenDtoFromJSON,
    PaymentTokenDtoFromJSONTyped,
    PaymentTokenDtoToJSON,
} from './PaymentTokenDto';

/**
 * 
 * @export
 * @interface CollectionTopBidDto
 */
export interface CollectionTopBidDto {
    /**
     * The ID of the marketplace
     * @type {string}
     * @memberof CollectionTopBidDto
     */
    marketplaceId: string;
    /**
     * The name of the marketplace
     * @type {string}
     * @memberof CollectionTopBidDto
     */
    marketplaceName: string;
    /**
     * The value of the bid
     * @type {number}
     * @memberof CollectionTopBidDto
     */
    value: number;
    /**
     * The payment token details
     * @type {PaymentTokenDto}
     * @memberof CollectionTopBidDto
     */
    paymentToken: PaymentTokenDto;
}

/**
 * Check if a given object implements the CollectionTopBidDto interface.
 */
export function instanceOfCollectionTopBidDto(value: object): boolean {
    if (!('marketplaceId' in value)) return false;
    if (!('marketplaceName' in value)) return false;
    if (!('value' in value)) return false;
    if (!('paymentToken' in value)) return false;
    return true;
}

export function CollectionTopBidDtoFromJSON(json: any): CollectionTopBidDto {
    return CollectionTopBidDtoFromJSONTyped(json, false);
}

export function CollectionTopBidDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionTopBidDto {
    if (json == null) {
        return json;
    }
    return {
        
        'marketplaceId': json['marketplace_id'],
        'marketplaceName': json['marketplace_name'],
        'value': json['value'],
        'paymentToken': PaymentTokenDtoFromJSON(json['payment_token']),
    };
}

export function CollectionTopBidDtoToJSON(value?: CollectionTopBidDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'marketplace_id': value['marketplaceId'],
        'marketplace_name': value['marketplaceName'],
        'value': value['value'],
        'payment_token': PaymentTokenDtoToJSON(value['paymentToken']),
    };
}

