/* tslint:disable */
/* eslint-disable */
/**
 * Once Upon
 * API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CollectionFloorPriceDto } from './CollectionFloorPriceDto';
import {
    CollectionFloorPriceDtoFromJSON,
    CollectionFloorPriceDtoFromJSONTyped,
    CollectionFloorPriceDtoToJSON,
} from './CollectionFloorPriceDto';
import type { CollectionTopBidDto } from './CollectionTopBidDto';
import {
    CollectionTopBidDtoFromJSON,
    CollectionTopBidDtoFromJSONTyped,
    CollectionTopBidDtoToJSON,
} from './CollectionTopBidDto';

/**
 * 
 * @export
 * @interface CollectionPriceDataDto
 */
export interface CollectionPriceDataDto {
    /**
     * Array of collection floor prices
     * @type {Array<CollectionFloorPriceDto>}
     * @memberof CollectionPriceDataDto
     */
    floorPrices: Array<CollectionFloorPriceDto>;
    /**
     * Array of collection top bids
     * @type {Array<CollectionTopBidDto>}
     * @memberof CollectionPriceDataDto
     */
    topBids: Array<CollectionTopBidDto>;
}

/**
 * Check if a given object implements the CollectionPriceDataDto interface.
 */
export function instanceOfCollectionPriceDataDto(value: object): boolean {
    if (!('floorPrices' in value)) return false;
    if (!('topBids' in value)) return false;
    return true;
}

export function CollectionPriceDataDtoFromJSON(json: any): CollectionPriceDataDto {
    return CollectionPriceDataDtoFromJSONTyped(json, false);
}

export function CollectionPriceDataDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionPriceDataDto {
    if (json == null) {
        return json;
    }
    return {
        
        'floorPrices': ((json['floorPrices'] as Array<any>).map(CollectionFloorPriceDtoFromJSON)),
        'topBids': ((json['topBids'] as Array<any>).map(CollectionTopBidDtoFromJSON)),
    };
}

export function CollectionPriceDataDtoToJSON(value?: CollectionPriceDataDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'floorPrices': ((value['floorPrices'] as Array<any>).map(CollectionFloorPriceDtoToJSON)),
        'topBids': ((value['topBids'] as Array<any>).map(CollectionTopBidDtoToJSON)),
    };
}

