/* tslint:disable */
/* eslint-disable */
/**
 * Once Upon
 * API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContextOutcomeTypeDto
 */
export interface ContextOutcomeTypeDto {
    /**
     * Key of the outcome
     * @type {string}
     * @memberof ContextOutcomeTypeDto
     */
    key: string;
    /**
     * Value of the outcome
     * @type {object}
     * @memberof ContextOutcomeTypeDto
     */
    value: object;
}

/**
 * Check if a given object implements the ContextOutcomeTypeDto interface.
 */
export function instanceOfContextOutcomeTypeDto(value: object): boolean {
    if (!('key' in value)) return false;
    if (!('value' in value)) return false;
    return true;
}

export function ContextOutcomeTypeDtoFromJSON(json: any): ContextOutcomeTypeDto {
    return ContextOutcomeTypeDtoFromJSONTyped(json, false);
}

export function ContextOutcomeTypeDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContextOutcomeTypeDto {
    if (json == null) {
        return json;
    }
    return {
        
        'key': json['key'],
        'value': json['value'],
    };
}

export function ContextOutcomeTypeDtoToJSON(value?: ContextOutcomeTypeDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'key': value['key'],
        'value': value['value'],
    };
}

