/* tslint:disable */
/* eslint-disable */
/**
 * Once Upon
 * API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContractCallRequestDto
 */
export interface ContractCallRequestDto {
    /**
     * Name of the method to be called on the contract.
     * @type {string}
     * @memberof ContractCallRequestDto
     */
    method: string;
    /**
     * Arguments for the method call.
     * @type {Array<string>}
     * @memberof ContractCallRequestDto
     */
    args: Array<string>;
}

/**
 * Check if a given object implements the ContractCallRequestDto interface.
 */
export function instanceOfContractCallRequestDto(value: object): boolean {
    if (!('method' in value)) return false;
    if (!('args' in value)) return false;
    return true;
}

export function ContractCallRequestDtoFromJSON(json: any): ContractCallRequestDto {
    return ContractCallRequestDtoFromJSONTyped(json, false);
}

export function ContractCallRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContractCallRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'method': json['method'],
        'args': json['args'],
    };
}

export function ContractCallRequestDtoToJSON(value?: ContractCallRequestDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'method': value['method'],
        'args': value['args'],
    };
}

