/* tslint:disable */
/* eslint-disable */
/**
 * Once Upon
 * API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateLabelDto
 */
export interface CreateLabelDto {
    /**
     * The address of the label.
     * @type {string}
     * @memberof CreateLabelDto
     */
    address: string;
    /**
     * The nickname of the label.
     * @type {string}
     * @memberof CreateLabelDto
     */
    nickname: string;
    /**
     * Indicates if the label is public.
     * @type {boolean}
     * @memberof CreateLabelDto
     */
    isPublic?: boolean;
}

/**
 * Check if a given object implements the CreateLabelDto interface.
 */
export function instanceOfCreateLabelDto(value: object): boolean {
    if (!('address' in value)) return false;
    if (!('nickname' in value)) return false;
    return true;
}

export function CreateLabelDtoFromJSON(json: any): CreateLabelDto {
    return CreateLabelDtoFromJSONTyped(json, false);
}

export function CreateLabelDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateLabelDto {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'],
        'nickname': json['nickname'],
        'isPublic': json['isPublic'] == null ? undefined : json['isPublic'],
    };
}

export function CreateLabelDtoToJSON(value?: CreateLabelDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'address': value['address'],
        'nickname': value['nickname'],
        'isPublic': value['isPublic'],
    };
}

