/* tslint:disable */
/* eslint-disable */
/**
 * Once Upon
 * API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DateRange
 */
export interface DateRange {
    /**
     * Start date range (inclusive)
     * @type {number}
     * @memberof DateRange
     */
    $gte?: number;
    /**
     * End date range (inclusive)
     * @type {number}
     * @memberof DateRange
     */
    $lte?: number;
}

/**
 * Check if a given object implements the DateRange interface.
 */
export function instanceOfDateRange(value: object): boolean {
    return true;
}

export function DateRangeFromJSON(json: any): DateRange {
    return DateRangeFromJSONTyped(json, false);
}

export function DateRangeFromJSONTyped(json: any, ignoreDiscriminator: boolean): DateRange {
    if (json == null) {
        return json;
    }
    return {
        
        '$gte': json['$gte'] == null ? undefined : json['$gte'],
        '$lte': json['$lte'] == null ? undefined : json['$lte'],
    };
}

export function DateRangeToJSON(value?: DateRange | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        '$gte': value['$gte'],
        '$lte': value['$lte'],
    };
}

