/* tslint:disable */
/* eslint-disable */
/**
 * Once Upon
 * API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EthPriceDto
 */
export interface EthPriceDto {
    /**
     * The price of the asset.
     * @type {number}
     * @memberof EthPriceDto
     */
    price: number;
    /**
     * Timestamp of the price data.
     * @type {number}
     * @memberof EthPriceDto
     */
    timestamp: number;
}

/**
 * Check if a given object implements the EthPriceDto interface.
 */
export function instanceOfEthPriceDto(value: object): boolean {
    if (!('price' in value)) return false;
    if (!('timestamp' in value)) return false;
    return true;
}

export function EthPriceDtoFromJSON(json: any): EthPriceDto {
    return EthPriceDtoFromJSONTyped(json, false);
}

export function EthPriceDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): EthPriceDto {
    if (json == null) {
        return json;
    }
    return {
        
        'price': json['price'],
        'timestamp': json['timestamp'],
    };
}

export function EthPriceDtoToJSON(value?: EthPriceDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'price': value['price'],
        'timestamp': value['timestamp'],
    };
}

