/* tslint:disable */
/* eslint-disable */
/**
 * Once Upon
 * API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GasPriceDto
 */
export interface GasPriceDto {
    /**
     * The price of the gas.
     * @type {number}
     * @memberof GasPriceDto
     */
    price: number;
    /**
     * Timestamp of the price data.
     * @type {number}
     * @memberof GasPriceDto
     */
    timestamp: number;
}

/**
 * Check if a given object implements the GasPriceDto interface.
 */
export function instanceOfGasPriceDto(value: object): boolean {
    if (!('price' in value)) return false;
    if (!('timestamp' in value)) return false;
    return true;
}

export function GasPriceDtoFromJSON(json: any): GasPriceDto {
    return GasPriceDtoFromJSONTyped(json, false);
}

export function GasPriceDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GasPriceDto {
    if (json == null) {
        return json;
    }
    return {
        
        'price': json['price'],
        'timestamp': json['timestamp'],
    };
}

export function GasPriceDtoToJSON(value?: GasPriceDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'price': value['price'],
        'timestamp': value['timestamp'],
    };
}

