/* tslint:disable */
/* eslint-disable */
/**
 * Once Upon
 * API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetSummaryDto
 */
export interface GetSummaryDto {
    /**
     * Addresses
     * @type {Array<string>}
     * @memberof GetSummaryDto
     */
    addresses: Array<string>;
    /**
     * ChainIds
     * @type {Array<string>}
     * @memberof GetSummaryDto
     */
    chainIds: Array<string>;
}

/**
 * Check if a given object implements the GetSummaryDto interface.
 */
export function instanceOfGetSummaryDto(value: object): boolean {
    if (!('addresses' in value)) return false;
    if (!('chainIds' in value)) return false;
    return true;
}

export function GetSummaryDtoFromJSON(json: any): GetSummaryDto {
    return GetSummaryDtoFromJSONTyped(json, false);
}

export function GetSummaryDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetSummaryDto {
    if (json == null) {
        return json;
    }
    return {
        
        'addresses': json['addresses'],
        'chainIds': json['chainIds'],
    };
}

export function GetSummaryDtoToJSON(value?: GetSummaryDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'addresses': value['addresses'],
        'chainIds': value['chainIds'],
    };
}

