/* tslint:disable */
/* eslint-disable */
/**
 * Once Upon
 * API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AddressWithChainIdDto } from './AddressWithChainIdDto';
import {
    AddressWithChainIdDtoFromJSON,
    AddressWithChainIdDtoFromJSONTyped,
    AddressWithChainIdDtoToJSON,
} from './AddressWithChainIdDto';

/**
 * 
 * @export
 * @interface GroupDto
 */
export interface GroupDto {
    /**
     * The unique ID of the group.
     * @type {string}
     * @memberof GroupDto
     */
    groupId: string;
    /**
     * The owner of the group.
     * @type {string}
     * @memberof GroupDto
     */
    owner: string;
    /**
     * The name of the group.
     * @type {string}
     * @memberof GroupDto
     */
    name: string;
    /**
     * List of addresses associated with the group, each with an array of chain IDs.
     * @type {Array<AddressWithChainIdDto>}
     * @memberof GroupDto
     */
    addresses: Array<AddressWithChainIdDto>;
}

/**
 * Check if a given object implements the GroupDto interface.
 */
export function instanceOfGroupDto(value: object): boolean {
    if (!('groupId' in value)) return false;
    if (!('owner' in value)) return false;
    if (!('name' in value)) return false;
    if (!('addresses' in value)) return false;
    return true;
}

export function GroupDtoFromJSON(json: any): GroupDto {
    return GroupDtoFromJSONTyped(json, false);
}

export function GroupDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupDto {
    if (json == null) {
        return json;
    }
    return {
        
        'groupId': json['groupId'],
        'owner': json['owner'],
        'name': json['name'],
        'addresses': ((json['addresses'] as Array<any>).map(AddressWithChainIdDtoFromJSON)),
    };
}

export function GroupDtoToJSON(value?: GroupDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'groupId': value['groupId'],
        'owner': value['owner'],
        'name': value['name'],
        'addresses': ((value['addresses'] as Array<any>).map(AddressWithChainIdDtoToJSON)),
    };
}

