/* tslint:disable */
/* eslint-disable */
/**
 * Once Upon
 * API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LabelDto
 */
export interface LabelDto {
    /**
     * The address of the label.
     * @type {string}
     * @memberof LabelDto
     */
    address: string;
    /**
     * The owner of the label.
     * @type {string}
     * @memberof LabelDto
     */
    owner: string;
    /**
     * The nickname of the label.
     * @type {string}
     * @memberof LabelDto
     */
    nickname: string;
    /**
     * Indicates if the label is public.
     * @type {boolean}
     * @memberof LabelDto
     */
    isPublic?: boolean;
}

/**
 * Check if a given object implements the LabelDto interface.
 */
export function instanceOfLabelDto(value: object): boolean {
    if (!('address' in value)) return false;
    if (!('owner' in value)) return false;
    if (!('nickname' in value)) return false;
    return true;
}

export function LabelDtoFromJSON(json: any): LabelDto {
    return LabelDtoFromJSONTyped(json, false);
}

export function LabelDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LabelDto {
    if (json == null) {
        return json;
    }
    return {
        
        'address': json['address'],
        'owner': json['owner'],
        'nickname': json['nickname'],
        'isPublic': json['isPublic'] == null ? undefined : json['isPublic'],
    };
}

export function LabelDtoToJSON(value?: LabelDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'address': value['address'],
        'owner': value['owner'],
        'nickname': value['nickname'],
        'isPublic': value['isPublic'],
    };
}

