/* tslint:disable */
/* eslint-disable */
/**
 * Once Upon
 * API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AssetDto } from './AssetDto';
import {
    AssetDtoFromJSON,
    AssetDtoFromJSONTyped,
    AssetDtoToJSON,
} from './AssetDto';

/**
 * 
 * @export
 * @interface NetAssetTransfersDto
 */
export interface NetAssetTransfersDto {
    /**
     * Received assets
     * @type {Array<AssetDto>}
     * @memberof NetAssetTransfersDto
     */
    received: Array<AssetDto>;
    /**
     * Sent assets
     * @type {Array<AssetDto>}
     * @memberof NetAssetTransfersDto
     */
    sent: Array<AssetDto>;
}

/**
 * Check if a given object implements the NetAssetTransfersDto interface.
 */
export function instanceOfNetAssetTransfersDto(value: object): boolean {
    if (!('received' in value)) return false;
    if (!('sent' in value)) return false;
    return true;
}

export function NetAssetTransfersDtoFromJSON(json: any): NetAssetTransfersDto {
    return NetAssetTransfersDtoFromJSONTyped(json, false);
}

export function NetAssetTransfersDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): NetAssetTransfersDto {
    if (json == null) {
        return json;
    }
    return {
        
        'received': ((json['received'] as Array<any>).map(AssetDtoFromJSON)),
        'sent': ((json['sent'] as Array<any>).map(AssetDtoFromJSON)),
    };
}

export function NetAssetTransfersDtoToJSON(value?: NetAssetTransfersDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'received': ((value['received'] as Array<any>).map(AssetDtoToJSON)),
        'sent': ((value['sent'] as Array<any>).map(AssetDtoToJSON)),
    };
}

