/* tslint:disable */
/* eslint-disable */
/**
 * Once Upon
 * API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NFTCollectionDto } from './NFTCollectionDto';
import {
    NFTCollectionDtoFromJSON,
    NFTCollectionDtoFromJSONTyped,
    NFTCollectionDtoToJSON,
} from './NFTCollectionDto';

/**
 * 
 * @export
 * @interface NftsByContractResponseDto
 */
export interface NftsByContractResponseDto {
    /**
     * Cursor for the next set of results
     * @type {string}
     * @memberof NftsByContractResponseDto
     */
    nextCursor: string;
    /**
     * URL for the next set of results
     * @type {string}
     * @memberof NftsByContractResponseDto
     */
    next?: string;
    /**
     * URL for the previous set of results
     * @type {string}
     * @memberof NftsByContractResponseDto
     */
    previous?: string;
    /**
     * Total count of NFTs
     * @type {number}
     * @memberof NftsByContractResponseDto
     */
    count: number;
    /**
     * List of NFT collections
     * @type {Array<NFTCollectionDto>}
     * @memberof NftsByContractResponseDto
     */
    nfts: Array<NFTCollectionDto>;
}

/**
 * Check if a given object implements the NftsByContractResponseDto interface.
 */
export function instanceOfNftsByContractResponseDto(value: object): boolean {
    if (!('nextCursor' in value)) return false;
    if (!('count' in value)) return false;
    if (!('nfts' in value)) return false;
    return true;
}

export function NftsByContractResponseDtoFromJSON(json: any): NftsByContractResponseDto {
    return NftsByContractResponseDtoFromJSONTyped(json, false);
}

export function NftsByContractResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): NftsByContractResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'nextCursor': json['next_cursor'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'count': json['count'],
        'nfts': ((json['nfts'] as Array<any>).map(NFTCollectionDtoFromJSON)),
    };
}

export function NftsByContractResponseDtoToJSON(value?: NftsByContractResponseDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'next_cursor': value['nextCursor'],
        'next': value['next'],
        'previous': value['previous'],
        'count': value['count'],
        'nfts': ((value['nfts'] as Array<any>).map(NFTCollectionDtoToJSON)),
    };
}

