/* tslint:disable */
/* eslint-disable */
/**
 * Once Upon
 * API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RenameGroupDto
 */
export interface RenameGroupDto {
    /**
     * The name of the group.
     * @type {string}
     * @memberof RenameGroupDto
     */
    name: string;
}

/**
 * Check if a given object implements the RenameGroupDto interface.
 */
export function instanceOfRenameGroupDto(value: object): boolean {
    if (!('name' in value)) return false;
    return true;
}

export function RenameGroupDtoFromJSON(json: any): RenameGroupDto {
    return RenameGroupDtoFromJSONTyped(json, false);
}

export function RenameGroupDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RenameGroupDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function RenameGroupDtoToJSON(value?: RenameGroupDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
    };
}

