/* tslint:disable */
/* eslint-disable */
/**
 * Once Upon
 * API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SigHashDto
 */
export interface SigHashDto {
    /**
     * Sender address
     * @type {string}
     * @memberof SigHashDto
     */
    from: string;
    /**
     * Receiver address
     * @type {string}
     * @memberof SigHashDto
     */
    to: string;
    /**
     * Signature hash
     * @type {string}
     * @memberof SigHashDto
     */
    sigHash: string;
}

/**
 * Check if a given object implements the SigHashDto interface.
 */
export function instanceOfSigHashDto(value: object): boolean {
    if (!('from' in value)) return false;
    if (!('to' in value)) return false;
    if (!('sigHash' in value)) return false;
    return true;
}

export function SigHashDtoFromJSON(json: any): SigHashDto {
    return SigHashDtoFromJSONTyped(json, false);
}

export function SigHashDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SigHashDto {
    if (json == null) {
        return json;
    }
    return {
        
        'from': json['from'],
        'to': json['to'],
        'sigHash': json['sigHash'],
    };
}

export function SigHashDtoToJSON(value?: SigHashDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'from': value['from'],
        'to': value['to'],
        'sigHash': value['sigHash'],
    };
}

