/* tslint:disable */
/* eslint-disable */
/**
 * Once Upon
 * API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TeamDto
 */
export interface TeamDto {
    /**
     * Name of the team
     * @type {string}
     * @memberof TeamDto
     */
    name: string;
    /**
     * Unique identifier of the team
     * @type {string}
     * @memberof TeamDto
     */
    teamId: string;
    /**
     * Whether the team is active or not
     * @type {boolean}
     * @memberof TeamDto
     */
    active: boolean;
    /**
     * List of admins in the team
     * @type {Array<string>}
     * @memberof TeamDto
     */
    admins: Array<string>;
    /**
     * List of members in the team
     * @type {Array<string>}
     * @memberof TeamDto
     */
    members: Array<string>;
}

/**
 * Check if a given object implements the TeamDto interface.
 */
export function instanceOfTeamDto(value: object): boolean {
    if (!('name' in value)) return false;
    if (!('teamId' in value)) return false;
    if (!('active' in value)) return false;
    if (!('admins' in value)) return false;
    if (!('members' in value)) return false;
    return true;
}

export function TeamDtoFromJSON(json: any): TeamDto {
    return TeamDtoFromJSONTyped(json, false);
}

export function TeamDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TeamDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'teamId': json['teamId'],
        'active': json['active'],
        'admins': json['admins'],
        'members': json['members'],
    };
}

export function TeamDtoToJSON(value?: TeamDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'teamId': value['teamId'],
        'active': value['active'],
        'admins': value['admins'],
        'members': value['members'],
    };
}

