/* tslint:disable */
/* eslint-disable */
/**
 * Once Upon
 * API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TokenDto
 */
export interface TokenDto {
    /**
     * 
     * @type {number}
     * @memberof TokenDto
     */
    chainId: number;
    /**
     * 
     * @type {string}
     * @memberof TokenDto
     */
    token: string;
    /**
     * 
     * @type {string}
     * @memberof TokenDto
     */
    owner: string;
    /**
     * 
     * @type {string}
     * @memberof TokenDto
     */
    netValue: string;
}

/**
 * Check if a given object implements the TokenDto interface.
 */
export function instanceOfTokenDto(value: object): boolean {
    if (!('chainId' in value)) return false;
    if (!('token' in value)) return false;
    if (!('owner' in value)) return false;
    if (!('netValue' in value)) return false;
    return true;
}

export function TokenDtoFromJSON(json: any): TokenDto {
    return TokenDtoFromJSONTyped(json, false);
}

export function TokenDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TokenDto {
    if (json == null) {
        return json;
    }
    return {
        
        'chainId': json['chainId'],
        'token': json['token'],
        'owner': json['owner'],
        'netValue': json['netValue'],
    };
}

export function TokenDtoToJSON(value?: TokenDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'chainId': value['chainId'],
        'token': value['token'],
        'owner': value['owner'],
        'netValue': value['netValue'],
    };
}

