/* tslint:disable */
/* eslint-disable */
/**
 * Once Upon
 * API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TraceDto
 */
export interface TraceDto {
    /**
     * Action details
     * @type {object}
     * @memberof TraceDto
     */
    action: object;
    /**
     * Block hash
     * @type {string}
     * @memberof TraceDto
     */
    blockHash: string;
    /**
     * Block number
     * @type {number}
     * @memberof TraceDto
     */
    blockNumber: number;
    /**
     * Result details
     * @type {object}
     * @memberof TraceDto
     */
    result: object;
    /**
     * Number of subtraces
     * @type {number}
     * @memberof TraceDto
     */
    subtraces: number;
    /**
     * Trace address
     * @type {Array<number>}
     * @memberof TraceDto
     */
    traceAddress: Array<number>;
    /**
     * Transaction hash
     * @type {string}
     * @memberof TraceDto
     */
    transactionHash: string;
    /**
     * Transaction position
     * @type {number}
     * @memberof TraceDto
     */
    transactionPosition: number;
    /**
     * Type of the trace
     * @type {string}
     * @memberof TraceDto
     */
    type: string;
}

/**
 * Check if a given object implements the TraceDto interface.
 */
export function instanceOfTraceDto(value: object): boolean {
    if (!('action' in value)) return false;
    if (!('blockHash' in value)) return false;
    if (!('blockNumber' in value)) return false;
    if (!('result' in value)) return false;
    if (!('subtraces' in value)) return false;
    if (!('traceAddress' in value)) return false;
    if (!('transactionHash' in value)) return false;
    if (!('transactionPosition' in value)) return false;
    if (!('type' in value)) return false;
    return true;
}

export function TraceDtoFromJSON(json: any): TraceDto {
    return TraceDtoFromJSONTyped(json, false);
}

export function TraceDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): TraceDto {
    if (json == null) {
        return json;
    }
    return {
        
        'action': json['action'],
        'blockHash': json['blockHash'],
        'blockNumber': json['blockNumber'],
        'result': json['result'],
        'subtraces': json['subtraces'],
        'traceAddress': json['traceAddress'],
        'transactionHash': json['transactionHash'],
        'transactionPosition': json['transactionPosition'],
        'type': json['type'],
    };
}

export function TraceDtoToJSON(value?: TraceDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'action': value['action'],
        'blockHash': value['blockHash'],
        'blockNumber': value['blockNumber'],
        'result': value['result'],
        'subtraces': value['subtraces'],
        'traceAddress': value['traceAddress'],
        'transactionHash': value['transactionHash'],
        'transactionPosition': value['transactionPosition'],
        'type': value['type'],
    };
}

