/* tslint:disable */
/* eslint-disable */
/**
 * Once Upon
 * API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ParamTypeDto } from './ParamTypeDto';
import {
    ParamTypeDtoFromJSON,
    ParamTypeDtoFromJSONTyped,
    ParamTypeDtoToJSON,
} from './ParamTypeDto';

/**
 * 
 * @export
 * @interface TransactionFragment
 */
export interface TransactionFragment {
    /**
     * Name of the fragment
     * @type {string}
     * @memberof TransactionFragment
     */
    name: string;
    /**
     * Type of the fragment
     * @type {string}
     * @memberof TransactionFragment
     */
    type: string;
    /**
     * Inputs of the fragment
     * @type {Array<ParamTypeDto>}
     * @memberof TransactionFragment
     */
    inputs: Array<ParamTypeDto>;
    /**
     * Outputs of the fragment
     * @type {Array<ParamTypeDto>}
     * @memberof TransactionFragment
     */
    outputs: Array<ParamTypeDto>;
    /**
     * Is the fragment constant
     * @type {boolean}
     * @memberof TransactionFragment
     */
    constant: boolean;
    /**
     * State mutability of the fragment
     * @type {string}
     * @memberof TransactionFragment
     */
    stateMutability: string;
    /**
     * Is the fragment payable
     * @type {boolean}
     * @memberof TransactionFragment
     */
    payable: boolean;
    /**
     * Gas value of the fragment
     * @type {string}
     * @memberof TransactionFragment
     */
    gas: string;
}

/**
 * Check if a given object implements the TransactionFragment interface.
 */
export function instanceOfTransactionFragment(value: object): boolean {
    if (!('name' in value)) return false;
    if (!('type' in value)) return false;
    if (!('inputs' in value)) return false;
    if (!('outputs' in value)) return false;
    if (!('constant' in value)) return false;
    if (!('stateMutability' in value)) return false;
    if (!('payable' in value)) return false;
    if (!('gas' in value)) return false;
    return true;
}

export function TransactionFragmentFromJSON(json: any): TransactionFragment {
    return TransactionFragmentFromJSONTyped(json, false);
}

export function TransactionFragmentFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionFragment {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'type': json['type'],
        'inputs': ((json['inputs'] as Array<any>).map(ParamTypeDtoFromJSON)),
        'outputs': ((json['outputs'] as Array<any>).map(ParamTypeDtoFromJSON)),
        'constant': json['constant'],
        'stateMutability': json['stateMutability'],
        'payable': json['payable'],
        'gas': json['gas'],
    };
}

export function TransactionFragmentToJSON(value?: TransactionFragment | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'type': value['type'],
        'inputs': ((value['inputs'] as Array<any>).map(ParamTypeDtoToJSON)),
        'outputs': ((value['outputs'] as Array<any>).map(ParamTypeDtoToJSON)),
        'constant': value['constant'],
        'stateMutability': value['stateMutability'],
        'payable': value['payable'],
        'gas': value['gas'],
    };
}

