/* tslint:disable */
/* eslint-disable */
/**
 * Once Upon
 * API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateLabelDto
 */
export interface UpdateLabelDto {
    /**
     * The nickname of the label.
     * @type {string}
     * @memberof UpdateLabelDto
     */
    nickname: string;
    /**
     * Flag indicating if the label is public.
     * @type {boolean}
     * @memberof UpdateLabelDto
     */
    isPublic?: boolean;
}

/**
 * Check if a given object implements the UpdateLabelDto interface.
 */
export function instanceOfUpdateLabelDto(value: object): boolean {
    if (!('nickname' in value)) return false;
    return true;
}

export function UpdateLabelDtoFromJSON(json: any): UpdateLabelDto {
    return UpdateLabelDtoFromJSONTyped(json, false);
}

export function UpdateLabelDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateLabelDto {
    if (json == null) {
        return json;
    }
    return {
        
        'nickname': json['nickname'],
        'isPublic': json['isPublic'] == null ? undefined : json['isPublic'],
    };
}

export function UpdateLabelDtoToJSON(value?: UpdateLabelDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'nickname': value['nickname'],
        'isPublic': value['isPublic'],
    };
}

