/* tslint:disable */
/* eslint-disable */
/**
 * Once Upon
 * API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AddressWithChainIdDto } from './AddressWithChainIdDto';
import {
    AddressWithChainIdDtoFromJSON,
    AddressWithChainIdDtoFromJSONTyped,
    AddressWithChainIdDtoToJSON,
} from './AddressWithChainIdDto';

/**
 * 
 * @export
 * @interface UpdateGroupDto
 */
export interface UpdateGroupDto {
    /**
     * The name of the group.
     * @type {string}
     * @memberof UpdateGroupDto
     */
    name: string;
    /**
     * List of addresses associated with the group, each with an array of chain IDs.
     * @type {Array<AddressWithChainIdDto>}
     * @memberof UpdateGroupDto
     */
    addresses: Array<AddressWithChainIdDto>;
    /**
     * Indicates if the group is public.
     * @type {boolean}
     * @memberof UpdateGroupDto
     */
    isPublic?: boolean;
}

/**
 * Check if a given object implements the UpdateGroupDto interface.
 */
export function instanceOfUpdateGroupDto(value: object): boolean {
    if (!('name' in value)) return false;
    if (!('addresses' in value)) return false;
    return true;
}

export function UpdateGroupDtoFromJSON(json: any): UpdateGroupDto {
    return UpdateGroupDtoFromJSONTyped(json, false);
}

export function UpdateGroupDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateGroupDto {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'addresses': ((json['addresses'] as Array<any>).map(AddressWithChainIdDtoFromJSON)),
        'isPublic': json['isPublic'] == null ? undefined : json['isPublic'],
    };
}

export function UpdateGroupDtoToJSON(value?: UpdateGroupDto | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'addresses': ((value['addresses'] as Array<any>).map(AddressWithChainIdDtoToJSON)),
        'isPublic': value['isPublic'],
    };
}

