import { userRoutes } from "./routes/user";
import { farcasterRoutes } from "./routes/farcaster";
import { farcasterSignerRoutes } from "./routes/farcaster/signer";
import { frameRoutes } from "./routes/frames";
import { contentRoutes } from "./routes/content";
import { notificationsRoutes } from "./routes/notifications";
import { degenRoutes } from "./routes/degen";
import { transactionRoutes } from "./routes/transactions";
import { flagRoutes } from "./routes/flags";
import { discoverRoutes } from "./routes/discover";
import { muteRoutes } from "./routes/user/mute";
import { panelRoutes } from "./routes/panel";
import { feedRoutes } from "./routes/feed";
import { pendingCastRoutes } from "./routes/pending";
import { farcasterFeedRoutes } from "./routes/farcaster/feed";
import { farconRoutes } from "./routes/farcon/attendees";
import { nftRoutes } from "./routes/nfts";
import { FastifyInstance } from "fastify";

export const registerV0Routes = async (fastify: FastifyInstance) => {
  fastify.register(contentRoutes, { prefix: "/v0" });
  fastify.register(userRoutes, { prefix: "/v0" });
  fastify.register(farcasterRoutes, { prefix: "/v0" });
  fastify.register(farcasterFeedRoutes, { prefix: "/v0" });
  fastify.register(farcasterSignerRoutes, { prefix: "/v0" });
  fastify.register(frameRoutes, { prefix: "/v0" });
  fastify.register(transactionRoutes, { prefix: "/v0" });
  fastify.register(notificationsRoutes, { prefix: "/v0" });
  fastify.register(flagRoutes, { prefix: "/v0" });
  fastify.register(degenRoutes, { prefix: "/v0" });
  fastify.register(discoverRoutes, { prefix: "/v0" });
  fastify.register(muteRoutes, { prefix: "/v0" });
  fastify.register(panelRoutes, { prefix: "/v0" });
  fastify.register(feedRoutes, { prefix: "/v0" });
  fastify.register(pendingCastRoutes, { prefix: "/v0" });
  fastify.register(farconRoutes, { prefix: "/v0" });
  fastify.register(nftRoutes, { prefix: "/v0" });
};
