/* tslint:disable */
/* eslint-disable */
/**
 * Once Upon
 * API documentation
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetSummaryDto,
} from '../models/index';
import {
    GetSummaryDtoFromJSON,
    GetSummaryDtoToJSON,
} from '../models/index';

export interface SummaryControllerSummarizeAddressesRequest {
    getSummaryDto: GetSummaryDto;
}

/**
 * 
 */
export class SummariesApi extends runtime.BaseAPI {

    /**
     * Provide an aggregated summary of all address activity for addresses provided.
     * Provide an aggregated summary of all address activity for addresses provided.
     */
    async summaryControllerSummarizeAddressesRaw(requestParameters: SummaryControllerSummarizeAddressesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<object>>> {
        if (requestParameters['getSummaryDto'] == null) {
            throw new runtime.RequiredError(
                'getSummaryDto',
                'Required parameter "getSummaryDto" was null or undefined when calling summaryControllerSummarizeAddresses().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/v1/summaries`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: GetSummaryDtoToJSON(requestParameters['getSummaryDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Provide an aggregated summary of all address activity for addresses provided.
     * Provide an aggregated summary of all address activity for addresses provided.
     */
    async summaryControllerSummarizeAddresses(requestParameters: SummaryControllerSummarizeAddressesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<object>> {
        const response = await this.summaryControllerSummarizeAddressesRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
